### ISSUE TITLE
HHAST fails to parse code from slack-sql-fake

### ISSUE THREAD

**Issue by lexidor** [hhvm/hhast#198]
I was linting their project and HHAST stopped with an exception at https://github.com/slackhq/hack-sql-fake/commit/2a5f48e87741549fc316ce55a5024a0bc65021e9
I stripped the file down until nothing could be removed without not causing it to crash. This is what I was left with.

```HACK
<?hh // strict

namespace Slack\SQLFake;

use type Facebook\CLILib\CLIWithArguments;
use namespace Facebook\CLILib\CLIOptions;

final class BuildSchemaCLI extends CLIWithArguments {
	<<__Override>>
	public async function mainAsync(): Awaitable<int> {
		return 0;
	}
	<<__Override>>
	public function getSupportedOptions(): vec<CLIOptions\CLIOption> {
		return vec[];
	}
}
```

I have no idea what is going wrong. I made sure to git clone a fresh one, change the composer.json required HHVM version to `^4.0.4`, run it immediately (without a broken hhast.parser-cache in place).

Here is my version info:
```
            "version": "v4.15.0",
            "source": {
                "type": "git",
                "url": "https://github.com/hhvm/hhast.git",
                "reference": "6b127b01616bf61139b931200320c901815ecf83"
            }

HipHop VM 4.15.0-dev (rel)
Compiler: heads/master-0-g51431335d2ece7eabb6961f49ad7e4cfd351d40b
Repo schema: b72970935c147f8095f9f8ec998ae5748eae9d02
```

Here is the exception and stacktrace (rather long)
```
Do not use "elseif", use "else if" instead.
  Linter: Facebook\HHAST\NoElseifLinter
  Location: /opt/lampp/htdocs/hack-sql-fake/src/Parser/ExpressionParser.php:399:14
@@ -396,7 +396,7 @@
                 throw new SQLFakeParseException('Unexpected keyword IN');
               }
               $this->expression = new InOperatorExpression($this->expression->left, $this->expression->negated);
-            } elseif ($operator === 'UNARY_MINUS' || $operator === 'UNARY_PLUS' || $operator === '~') {
+            } else if ($operator === 'UNARY_MINUS' || $operator === 'UNARY_PLUS' || $operator === '~') {
               $this->expression as PlaceholderExpression;
               $this->expression = new UnaryExpression($operator);
             } else {
Would you like to apply this fix?
  <yes to all>
A linter threw an exception:
  Linter: Facebook\HHAST\PreferLambdasLinter
  File: /opt/lampp/htdocs/hack-sql-fake/src/BuildSchemaCLI.php
  Exception: Facebook\HHAST\ASTDeserializationError
  Message: In file "/opt/lampp/htdocs/hack-sql-fake/src/BuildSchemaCLI.php": Failed to deserialize AST: Argument 1 to Facebook\HHAST\MethodishDeclarationGeneratedBase::__construct() must be of type ?Facebook\HHAST\OldAttributeSpecification, Facebook\HHAST\AttributeSpecification given
    8 final class BuildSchemaCLI extends CLIWithArguments {
    9   <<__Override>>
      ^ HERE
  Trace:
    #0 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/nodes/Node.hack(132): Facebook\HHAST\__Private\node_from_json()
    #1 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/nodes/NodeList.hack(107): Facebook\HHAST\Node::fromJSON()
    #2 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/codegen/node_from_json.hack(227): Facebook\HHAST\NodeList::fromJSON()
    #3 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/__Private/node_from_json.hack(28): Facebook\HHAST\__Private\node_from_json_unwrapped()
    #4 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/nodes/Node.hack(132): Facebook\HHAST\__Private\node_from_json()
    #5 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/codegen/syntax/ClassishBody.hack(55): Facebook\HHAST\Node::fromJSON()
    #6 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/codegen/node_from_json.hack(227): Facebook\HHAST\ClassishBody::fromJSON()
    #7 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/__Private/node_from_json.hack(28): Facebook\HHAST\__Private\node_from_json_unwrapped()
    #8 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/nodes/Node.hack(132): Facebook\HHAST\__Private\node_from_json()
    #9 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/codegen/syntax/ClassishDeclaration.hack(154): Facebook\HHAST\Node::fromJSON()
    #10 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/codegen/node_from_json.hack(227): Facebook\HHAST\ClassishDeclarationGeneratedBase::fromJSON()
    #11 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/__Private/node_from_json.hack(28): Facebook\HHAST\__Private\node_from_json_unwrapped()
    #12 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/nodes/Node.hack(132): Facebook\HHAST\__Private\node_from_json()
    #13 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/nodes/NodeList.hack(107): Facebook\HHAST\Node::fromJSON()
    #14 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/codegen/node_from_json.hack(227): Facebook\HHAST\NodeList::fromJSON()
    #15 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/__Private/node_from_json.hack(28): Facebook\HHAST\__Private\node_from_json_unwrapped()
    #16 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/nodes/Node.hack(132): Facebook\HHAST\__Private\node_from_json()
    #17 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/codegen/syntax/Script.hack(40): Facebook\HHAST\Node::fromJSON()
    #18 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/__Private/from_decoded_json.hack(29): Facebook\HHAST\ScriptGeneratedBase::fromJSON()
    #19 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/entrypoints.hack(81): Facebook\HHAST\__Private\from_decoded_json()
    #20 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/__Private/InMemoryFileKeyedCache.hack(36): Facebook\HHAST\from_file_async()
    #21 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/Linters/ASTLinter.hack(47): Closure$Facebook\HHAST\__Private\InMemoryFileKeyedCache::fetchAsync()
    #22 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/__Private/LintRun.hack(114): Facebook\HHAST\ASTLinter->getLintErrorsAsync()
    #23 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/__Private/LintRun.hack(80): Facebook\HHAST\__Private\LintRun->runLinterOnFileImplAsync()
    #24 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hsl/src/vec/async.php(83): Closure$Facebook\HHAST\__Private\LintRun::lintFileAsync()
    #25 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/__Private/LintRun.hack(93): HH\Lib\Vec\map_async()
    #26 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/__Private/LintRun.hack(151): Facebook\HHAST\__Private\LintRun->lintFileAsync()
    #27 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hsl/src/vec/async.php(83): Closure$Facebook\HHAST\__Private\LintRun::lintDirectoryAsync()
    #28 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/__Private/LintRun.hack(152): HH\Lib\Vec\map_async()
    #29 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/__Private/LintRun.hack(165): Facebook\HHAST\__Private\LintRun->lintDirectoryAsync()
    #30 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/__Private/LintRun.hack(59): Facebook\HHAST\__Private\LintRun->lintPathAsync()
    #31 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hsl/src/vec/async.php(83): Closure$Facebook\HHAST\__Private\LintRun::runAsync()
    #32 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/__Private/LintRun.hack(61): HH\Lib\Vec\map_async()
    #33 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/__Private/LinterCLI.hack(150): Facebook\HHAST\__Private\LintRun->runAsync()
    #34 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/src/__Private/LinterCLI.hack(73): Facebook\HHAST\__Private\LinterCLI->mainImplAsync()
    #35 /opt/lampp/htdocs/hack-sql-fake/vendor/facebook/hh-clilib/src/CLIBase.hack(181): Facebook\HHAST\__Private\LinterCLI->mainAsync()
    #36 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/bin/hhast-lint.hack(38): Facebook\CLILib\CLIBase::runAsync()
    #37 /opt/lampp/htdocs/hack-sql-fake/vendor/hhvm/hhast/bin/hhast-lint(21): Facebook\HHAST\__Private\hhast_lint_main_async()
    #38 (): Facebook\HHAST\__Private\hhast_lint_main_async_UNSAFE()
    #39 (): Closure$__SystemLib\enter_async_entry_point()
    #40 (): HH\Asio\join()
    #41 (): __SystemLib\enter_async_entry_point()
    #42 {main}
```

**Comment by fredemmott** [comment]
HHAST 4.15 requires HHVM 4.15; your build is quite far behind

```
$ git log --oneline 51431335d2ece7eabb6961f49ad7e4cfd351d40b..HHVM-4.15.
2dbd961ad6 Releasing 4.15.0
a690d95c20 don't write to hive when running tests
2aacbeccb8 Fixed FFP test failures
307187e5d7 Fix failing build caused by missing parameter
bd7d06c5df Do better at resolving the parent class in hhbbc.
1ec2de96b8 Fix a test to not try to return int from a ":void" function.
afd1a0c089 Improve assertion error msg in IRInstruction::src()
9fd2a3764f (Hack) Expose enum attributes through Facts
5d9dca67f8 updating fbcode to supercaml 1.10 (ocaml 4.07.1)
84605303e2 Tests for new error codes
90ed7bc907 hhi fixes for new error codes
9d528d1542 Thread error callback through subtyping code
c7b3f652be Allow top-level requires in strict mode files by default
6db1b78275 Support Facts deserialization from JSON
d6928dfc8b Modify typing_check_lru_service to be more similar to typing_check_service
9d48b0bd2e Add lru_worker stub to dune
ba8b11ea13 Support coercion from abstract types to enforceable types
c65d5ba7e7 Update hackfmt with better attribute handling
3a9dba3c5d Add a new option to use inference results in the typed ast
a5217af211 Parser support for RecordArray instantiation
db581fe965 Replace vec by slice
a3f6573799 Implement new attribute syntax
cc1a69636c Constructing Ocaml value directly
342e3962a0 Do not select default type for abstract typeconsts in interfaces and traits
3c19304c97 Handle AtomicLowPtr in rawptr
917d8370bd Add new provider_config for Lru_shared_memory
4e8ad2f94e Add integration test for `textDocument/definition`
e349ba3f0f Add integration test for `textDocument/hover`
e113726bb2 Support `telemetry/event` notifications in LSP tests
c9003726eb Support loading a specified naming table saved-state from disk
895e2376ac Refactor coroutine smart constructor
9ff2e6bd6b Add configurable list for fixmes disallowed in decl positions.
8050794805 Do not consider ancestors included via a require-implements relationship to be synthesized
4f275825e2 Parser option to disallow top-level require statements
94dd0e037a avoid null dereferencing when gathering memory stats
4b259b492f Add space after attributes on parameter declarations
db00e7ef7d Log precise hh_server startup time
467476f533 Fix issues with ClsRefGetTS JIT implementation
c4065ee72d Batch files in groups of 500 and update percentage monitor
f9c9e547ab fix Obj_get
89cafffacd Move scripts to opt-clang
c1ad415ff1 Improve typing for `noreturn` annotated methods.
9abc78d93f Fix inout function name check
d6c125a88e Refactor syntax smart constructor state
5dd3f6ab31 Fix one more $argv[0] interpolation in run.php
228c742457 Don't use the unsound feature "bind by move"
9a8eb34cea Move rx_move_check out of nastCheck
4dbd1665b5 Disallow top-level require statements
5a20c83f8e Add commandline tool to upload symbol information to Glean
bcd0f89b27 Add back support for coercing class_meth(), fun(), and class pointers on builtins
46dda8861d Default DisableInstanceof option to true
f4d3216542 Add flag and functionality to disable the ability to HH_FIXME or HH_IGNORE_ERROR 5000-5999 codes
0363e5bb34 Unify newtype and enum representations
7b2b08d4cc Enforce invariants of const classes/properties in the assembler.
6f7339e16d Enforce invariants of const classes/properties in the parser.
c44e39d0b3 Delete AttrHasConstProps.
7ff3237de1 Stop using AttrHasConstProps in hhbbc.
21f3b1ae8e Stop using AttrHasConstProps in the runtime.
d3db3220d0 Remove await_not_allowed from NastCheck
bab055e8eb Fix OOM error when collecting symbol info over WWW
2662509a08 show at least some signal in serverRage
b226a3653b fix CLI client exit (#8531)
a4998eb2b9 Implements functionality for Json writer based on Glean Schema
dc36ee0e09 Fix printir annotations
213704020e Collect worker memory stats
d1b8d508f1 Adapt Class_get to class-level where clauses
13696bfa66 Remove namespace results from symbol search
ccf048d1cf Revert D16229007: [hack] Unban reification of dynamic and functions
12fbec9736 simplify_unions always calls simplify_intersections
b3a0ad33c6 Inout parameters should be treated invariantly for purposes of tyvars
96474126ea Avoid int32 overflow in HFSort
d82fb253e4 Fix clippy warnings
```

In particular, your build does not have a3f6573799
