### ISSUE TITLE
hhast-migrate --hhvm-3.22-to-3.23 crashes on facebook/definition-finder

### ISSUE THREAD

**Issue by eryi** [hhvm/hhast#9]
Tested on HipHop VM 3.22.0 (rel)
````
composer require facebook/definition-finder
bin/hhast-migrate --hhvm-3.22-to-3.23 vendor/facebook/definition-finder
````
Error
````
Fatal error: Uncaught exception 'Exception' with message 'unexpected JSON kind: extra_token_error' in hhast/codegen/editable_node_from_json.php:371
Stack trace:
#0 hhast/src/EditableNode.php(129): Facebook\HHAST\__Private\editable_node_from_json()
#1 hhast/src/EditableToken.php(145): Facebook\HHAST\EditableNode::fromJSON()
#2 hhast/src/__Private/fold_map.php(24): Closure$Facebook\HHAST\EditableToken::fromJSON()
#3 hhast/src/EditableToken.php(148): Facebook\HHAST\__Private\fold_map()
#4 hhast/codegen/editable_node_from_json.php(21): Facebook\HHAST\EditableToken::fromJSON()
#5 hhast/src/EditableNode.php(129): Facebook\HHAST\__Private\editable_node_from_json()
#6 hhast/codegen/syntax/FunctionCallExpression.php(58): Facebook\HHAST\EditableNode::fromJSON()
#7 hhast/codegen/editable_node_from_json.php(241): Facebook\HHAST\FunctionCallExpression::fromJSON()
#8 hhast/src/EditableNode.php(129): Facebook\HHAST\__Private\editable_node_from_json()
#9 hhast/codegen/syntax/ExpressionStatement.php(34): Facebook\HHAST\EditableNode::fromJSON()
#10 hhast/codegen/editable_node_from_json.php(132): Facebook\HHAST\ExpressionStatement::fromJSON()
#11 hhast/src/EditableNode.php(129): Facebook\HHAST\__Private\editable_node_from_json()
#12 hhast/src/EditableList.php(92): Facebook\HHAST\EditableNode::fromJSON()
#13 hhast/codegen/editable_node_from_json.php(23): Facebook\HHAST\EditableList::fromJSON()
#14 hhast/src/EditableNode.php(129): Facebook\HHAST\__Private\editable_node_from_json()
#15 hhast/codegen/syntax/Script.php(29): Facebook\HHAST\EditableNode::fromJSON()
#16 hhast/codegen/editable_node_from_json.php(47): Facebook\HHAST\Script::fromJSON()
#17 hhast/src/EditableNode.php(129): Facebook\HHAST\__Private\editable_node_from_json()
#18 hhast/src/entrypoints.php(20): Facebook\HHAST\EditableNode::fromJSON()
#19 hhast/src/entrypoints.php(36): Facebook\HHAST\from_json()
#20 hhast/src/__Private/MigrationCLI.php(57): Facebook\HHAST\from_file()
#21 hhast/src/__Private/MigrationCLI.php(74): Facebook\HHAST\__Private\MigrationCLI->migrateFile()
#22 hhast/src/__Private/MigrationCLI.php(98): Facebook\HHAST\__Private\MigrationCLI->migrateDirectory()
#23 hhast/bin/hhast-migrate(18): Facebook\HHAST\__Private\MigrationCLI->mainAsync()
#24 {main}
````

By default, `hhast-migrate --hhvm-3.22-to-3.23` migrates the vendor directory as well.
`facebook/definition-finder` is used by `hhvm/hhvm-autoload` so a many projects might be affected.

**Comment by fredemmott** [comment]
I'll look into why it's crashing on definition-finder.

It will run on exactly what you tell it to - you probably don't want to run it on vendor (or your project root) if you're using composer - but others use that directory name differently. You probably want to run it on $ROOT/{bin,src} or similar.

**Comment by fredemmott** [comment]
actually, yeah, let's ignore vendor/ by default and add a flag not to. This case should be much more common than the "vendor isn't special" case

**Comment by fredemmott** [comment]
https://github.com/hhvm/hhast/releases/tag/v0.2
